/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 turbine.gltf
Author: blenderbirb (https://sketchfab.com/blenderbirb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/turbine-turbofan-engine-jet-engine-74c6aceed86b4a41aaad3b93afc3e262
Title: Turbine | Turbofan Engine | Jet Engine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/turbine.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.03}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['metal-bright']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['plastic-cone-black']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['plastic-grey']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['accent-yellow']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['accent-yellow']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['accent-yellow']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['metal-bright']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['metal-bright']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['metal-bright']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['metal-dark']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['metal-dark']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['metal-dark']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['metal-mid']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['metal-mid']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['metal-mid']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['metal-mid']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['metal-mid']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['metal-mid']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['metal-mid']} />
      </group>
    </group>
  )
}

useGLTF.preload('/turbine.gltf')
